### ISSUE TITLE
Python implemetation to save and load in_memory dynamic index

### ISSUE THREAD

**Issue by shreyasraoverse** [microsoft/DiskANN#400]
Hi,

I have trying to save an in memory dynamic index using the python wrapper diskannpy. I have tried both cases of compact_before_save - True and False.

When I set compact_before_save = True, the data seems to be corrupted. The reason being, when I try to load the index, using the from_file class_method, I get different values for size(_location_to_tag) and _tag_to_location

done. Index has 1000001 nodes and 55 out-edges, _start is set to 1000000                                                                                                                 
Num frozen points:1 _nd: 1000000 _start: 10000000 size(_location_to_tag): 1000000 size(_tag_to_location):1 Max points: 10000000                                                          

When I try to set compact_before_save = False, I am not able to save. There is a Segmentation fault (core dumped) encountered.

Can anyone please help?

Thanks

**Comment by daxpryce** [comment]
@shreyasraoverse - I'm just collecting more data from you so I can repro this in test and work on a fix. 

Can you tell me what you did between loading from file and trying to save?  Was it both insert and delete or just one of them?

**Comment by daxpryce** [comment]
@shreyasraoverse Can you let me know whether https://github.com/microsoft/DiskANN/blob/fef782c7cadbc473c6271660716d27653db92277/python/tests/test_dynamic_memory_index.py#L301 is a fair example of this bug?  Can you post a snippet of the sequence of call patterns you made prior to trying to save and then load again so I can make sure I'm using it the same way you were?

**Comment by daxpryce** [comment]
This just in: we also cannot yet save an uncompacted index. So deletes MUST be consolidated first, and compact_before_save must always be True.  I'm making changes now to make that be the case and removing the parameter, which I will add back in once we have that actually working.

**Comment by daxpryce** [comment]
#402 is associated with this issue as well

**Comment by daxpryce** [comment]
I believe #404 will fix this issue, as I understand it.  If it doesn't, please reopen and @ me so I can make some other fixes.

**Comment by shreyasraoverse** [comment]
@daxpryce #404 didnot fix the issue. The tags that are getting loaded seem to be gibberish; as in none of the tags that were used to create the index in the first place are present in the loaded index. Pleae do check that as well when you are running the test case [here](https://github.com/microsoft/DiskANN/blob/main/python/tests/test_dynamic_memory_index.py)
add this as well. To ellaborate, tags from index.search and tags from index2.search are different.

**Comment by daxpryce** [comment]
Did you happen to notice if the tags as a set different, or has their ordering changed?  Compaction and consolidation results in a new tag schema, in that the tag/identifier in the tags file will be in a different location, though I don't know if it's completely randomized or just simply compacted.

Also just as an FYI, in the comments [here](https://github.com/microsoft/DiskANN/issues/394#issuecomment-1652903241) and [here](https://github.com/microsoft/DiskANN/issues/394#issuecomment-1652904086) you added a `_data_compacted=false;` and a also mentioned it wasn't defined anywhere; I just wanted to point out that it's defined in the `index.h` file: https://github.com/microsoft/DiskANN/blob/main/include/index.h#L418

I'm going to dive back into more tests of the resultant tags files. Thanks for your reports; they're exactly the sorts of reports we need!

**Comment by daxpryce** [comment]
@shreyasraoverse 

I *am* seeing a single semi-unexpected value in the returned tagset after saving a dynamic index again in my unit test. It's the reserved tag `0`, which we reserve because we need to guarantee it's existence for the graph traversal part of the vamana indexing algorithm. So we don't let the user initially send us a tag of 0, as we're going to need to ensure it is always there. It subsequently gets written out in the resulting tags file with any saves of the `DynamicMemoryIndex` .

Otherwise, the tags files, when read in and treated as a set, are identical. This is to be expected, as this tag file is used to map vector location in a compacted array with a tag id in a likewise compacted array. These vectors get shuffled internally as part of the reindexing process, which means their line number in the file is the new corresponding location of the vector in the diskann Vector vector (as in, the vector holding all the vectors). 

So if you were expecting it to mostly be in the same order as it was prior, it would look like gibberish, but if you instead look at is as an unordered set, it ends up being correct.

Or at least, I think that's what we're doing.  The inner parts of diskann have some subtle nuance and I don't claim to be an expert in that arena.

**Comment by daxpryce** [comment]
Here's my updated test that I used to verify the tag file seems to be right.  Could I ask you try it on your end  @shreyasraoverse? Especially without you manually setting `_data_compacted=false;` in index.cpp (maybe create a fresh venv and install 0.5.0rc5 just to run the test against it?)  I don't want to be inadvertently gaslighting you just because it does seem to be working correctly on my end.  Also, maybe my unit test just isn't triggering it, and your current dataset is?

```python
    # Issue #400
    def test_issue400(self):
        _, _, _, index_vectors, ann_dir, _, generated_tags = self._test_matrix[0]

        orig_tag_set = set(generated_tags.tolist())
        inserted_tags = set()

        deletion_tag = generated_tags[10]  # arbitrary choice
        deletion_vector = index_vectors[10]

        index = dap.DynamicMemoryIndex.from_file(
            index_directory=ann_dir,
            num_threads=16,
            initial_search_complexity=32,
            max_vectors=10100,
            complexity=64,
            graph_degree=32
        )
        index.insert(np.array([1.0] * 10, dtype=np.single), 10099)
        index.insert(np.array([2.0] * 10, dtype=np.single), 10050)
        index.insert(np.array([3.0] * 10, dtype=np.single), 10053)
        inserted_tags.add(10099)
        inserted_tags.add(10050)
        inserted_tags.add(10053)

        tags, distances = index.search(np.array([3.0] * 10, dtype=np.single), k_neighbors=5, complexity=64)
        self.assertIn(10053, tags)
        tags, distances = index.search(deletion_vector, k_neighbors=5, complexity=64)
        self.assertIn(deletion_tag, tags, "deletion_tag should exist, as we have not deleted yet")
        index.mark_deleted(deletion_tag)

        expected_tags = orig_tag_set.union(inserted_tags)
        expected_tags.remove(deletion_tag)

        tags, distances = index.search(deletion_vector, k_neighbors=5, complexity=64)
        self.assertNotIn(deletion_tag, tags, "deletion_tag should not exist, as we have marked it for deletion")
        with tempfile.TemporaryDirectory() as tmpdir:
            index.save(tmpdir)

            index2 = dap.DynamicMemoryIndex.from_file(
                index_directory=tmpdir,
                num_threads=16,
                initial_search_complexity=32,
                max_vectors=10100,
                complexity=64,
                graph_degree=32
            )

            tags_path = os.path.join(tmpdir, "ann.tags")
            tags2 = dap.vectors_from_binary(tags_path, dtype=np.uint32)  # mypy won't like this, but it should work
            tags2_set = set(tags2.reshape(tags2.shape[0]).tolist())
            # we expect 0 to be added, but it can never be a tag in the original set because it's reserved
            # so we're removing it for the purposes of comparison
            tags2_set.remove(0)
            self.assertSetEqual(expected_tags, tags2_set)

            tags, distances = index2.search(deletion_vector, k_neighbors=5, complexity=64)
            self.assertNotIn(
                deletion_tag,
                tags,
                "deletion_tag should not exist, as we saved and reloaded the index without it"
            )
```

**Comment by daxpryce** [comment]
@shreyasraoverse have you had an opportunity to verify if it is a gibberish set of tags or if it is just ordered differently?

**Comment by daxpryce** [comment]
Closing this as there has been no new information.  We can certainly reopen if we get new bug information
